<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite name="com.acams.ddf.testcases.DemographicsPageTest" tests="3" time="109.076" ignored="0" failures="1" timestamp="05 Feb 2018 12:46:51 GMT" skipped="2" hostname="AcroLap15" errors="0">
  <testcase name="DemographicsPageTest" time="77.787" classname="com.acams.ddf.testcases.DemographicsPageTest">
    <skipped/>
  </testcase> <!-- DemographicsPageTest -->
  <testcase name="DemographicsPageTest" time="6.364" classname="com.acams.ddf.testcases.DemographicsPageTest">
    <failure type="java.lang.AssertionError" message="test case t2 block got executed">
      <![CDATA[java.lang.AssertionError: test case t2 block got executed
	at org.testng.Assert.fail(Assert.java:94)
	at com.acams.ddf.base.BaseTest.reportFailure(BaseTest.java:815)
	at com.acams.ddf.testcases.DemographicsPageTest.DemographicsPageTest(DemographicsPageTest.java:152)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:998)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1200)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- DemographicsPageTest -->
  <testcase name="DemographicsPageTest" time="24.925" classname="com.acams.ddf.testcases.DemographicsPageTest">
    <skipped/>
  </testcase> <!-- DemographicsPageTest -->
</testsuite> <!-- com.acams.ddf.testcases.DemographicsPageTest -->
